// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP1YjOTP1W6aSA3q-4pTB7OtTG5ouF7Fk',
    appId: '1:63965138386:web:00fcdfa830a32cf3d84c0b',
    messagingSenderId: '63965138386',
    projectId: 'hydroponic-store',
    authDomain: 'hydroponic-store.firebaseapp.com',
    storageBucket: 'hydroponic-store.appspot.com',
    measurementId: 'G-RS5TP8XWSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmAUMeVuIkZGtp4ptl3_TIdB6rDUCtows',
    appId: '1:63965138386:android:03c22556bf4f4427d84c0b',
    messagingSenderId: '63965138386',
    projectId: 'hydroponic-store',
    storageBucket: 'hydroponic-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOVx4pPWGvKdY67WzJVy6kBX-V8Ti4C6o',
    appId: '1:63965138386:ios:933704173d01566cd84c0b',
    messagingSenderId: '63965138386',
    projectId: 'hydroponic-store',
    storageBucket: 'hydroponic-store.appspot.com',
    androidClientId: '63965138386-cdcbkce47gj3aujp642e9p06k3q9kck6.apps.googleusercontent.com',
    iosClientId: '63965138386-4s7k5e86mls57rhcvnt6gv72u4d4gora.apps.googleusercontent.com',
    iosBundleId: 'com.hydroponics.hydroponicsStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOVx4pPWGvKdY67WzJVy6kBX-V8Ti4C6o',
    appId: '1:63965138386:ios:933704173d01566cd84c0b',
    messagingSenderId: '63965138386',
    projectId: 'hydroponic-store',
    storageBucket: 'hydroponic-store.appspot.com',
    androidClientId: '63965138386-cdcbkce47gj3aujp642e9p06k3q9kck6.apps.googleusercontent.com',
    iosClientId: '63965138386-4s7k5e86mls57rhcvnt6gv72u4d4gora.apps.googleusercontent.com',
    iosBundleId: 'com.hydroponics.hydroponicsStore',
  );
}
